package com.sonyericsson.hudson.plugins.gerrit.trigger.config;

import org.junit.jupiter.api.Test;

import static org.junit.Assert.assertEquals;

/**
 * @author schemuwel &lt;schemuwel@gmail.com&gt;
 */
public class CommandBuilderTests {

    /**
     * Test for building command using placeholder values (e.g. global configuration command template)
     */
    @Test
    public void testBuildForPlaceholderValues() {
        CommandBuilder commandBuilder = new CommandBuilder()
                .WithChange("<CHANGE>")
                .WithPatchset("<PATCHSET>")
                .WithMessage("Build Started <BUILDURL> <STARTED_STATS>")
                .WithLabel("UI-VALIdation");

        String command = commandBuilder.build();

        assertEquals("gerrit review <CHANGE>,<PATCHSET> --message 'Build Started <BUILDURL> <STARTED_STATS>'" +
                " --verified <VERIFIED> --code-review <CODE_REVIEW> --ui-validation <UI_VALIDATION> --tag autogenerated:jenkins-gerrit-trigger", command);
    }

    /**
     * Test for building command using real values (e.g. values for Gerrit events)
     */
    @Test
    public void testBuildWithRealValues() {
        CommandBuilder commandBuilder = new CommandBuilder()
                .WithChange("529381")
                .WithPatchset("10")
                .WithMessage("Build Started https://jenkins.example.com/job/529381/10/ (1 tests failed)")
                .WithLabel("Code-Review", "-1")
                .WithLabel("Verified", "-1")
                .WithLabel("Custom-LABEL", "2");

        String command = commandBuilder.build();

        assertEquals("gerrit review 529381,10 --message 'Build Started https://jenkins.example.com/job/529381/10/ (1 tests failed)'" +
                " --verified -1 --custom-label 2 --code-review -1 --tag autogenerated:jenkins-gerrit-trigger", command);
    }


    /**
     * Test for creating command from string (e.g. when parsing the global configuration)
     */
    @Test
    public void testFromString() {
        String command = "gerrit review --message 'Build Started <BUILDURL> <STARTED_STATS>'" +
                " --verified <VERIFIED> --code-review <CODE_REVIEW> <CHANGE>,<PATCHSET> --validated <VALIDATED>";

        CommandBuilder commandBuilder = CommandBuilder.fromString(command);
        String parsedCommand = commandBuilder.build();

        assertEquals("gerrit review <CHANGE>,<PATCHSET> --message 'Build Started <BUILDURL> <STARTED_STATS>'" +
                " --verified <VERIFIED> --validated <VALIDATED> --code-review <CODE_REVIEW> --tag autogenerated:jenkins-gerrit-trigger", parsedCommand);
    }
}
